name: Build

on:
  pull_request:
    branches:
      - main  # Runs when there's a PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "Tests failed"
